version: "3.7"

services:
  app:
    build:
      context: .
    restart: always
    volumes:
      - ./:/app
    command: python ./app.py

  python:
    build: 
      context: .
    restart: always
    command: tail -f /dev/null
    volumes:
      - ./:/app